version: '2'

services:

  mysql:
    image: mysql:8.0.13
    container_name: algafood-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 416424
    ports:
      - "3306:3306"
    volumes:
      - ./local/db:/local/db
